### ISSUE TITLE
dbg!

### ISSUE THREAD

**Issue by mo8it** [nikitavoloboev/log_macro#1]
You link to [`dbg!`](https://doc.rust-lang.org/stable/std/macro.dbg.html) in your README so I guess you know about it. For me, it basically does all what this macro does and even plans to do. Am I missing something?

Plus, commit messages are there for a reason. It is not helpful when all messages are `.`

**Comment by nikivdev** [comment]
My issue with `dbg!` was that it had a lot of extra info that I did not need. When I debug I just needed the variable name + the value behind it.

This macro recently added color to variables too so its quick to see them amongst many logs.

<img width="242" alt="image" src="https://github.com/nikitavoloboev/log_macro/assets/6391776/f53887e6-a36d-4b66-8319-76d15119a2df">

> commit messages are there for a reason

yea will fix that, just have lots of things to do right now
